# Author: Alessandra Fais
# Date: 04/06/2019

all:
	$(MAKE) -C src

test_main_map:
	$(MAKE) test_main_map -C src

test_main_keyfarm:
	$(MAKE) test_main_keyfarm -C src

clean:
	$(MAKE) clean -C src

.DEFAULT_GOAL := all
.PHONY: all test_main_map clean
