# Author: Alessandra Fais
# Date: 13/06/2019

all:
	$(MAKE) -C src

test_main:
	$(MAKE) test_main -C src

test_gdal:
	$(MAKE) test_gdal -C src

clean:
	$(MAKE) clean -C src

.DEFAULT_GOAL := all
.PHONY: all test_main test_gdal clean
