# Author: Alessandra Fais
# Date: 16/05/2019

all:
	$(MAKE) -C src

test_main_map:
	$(MAKE) test_main_map -C src

test_main_keyfarm:
	$(MAKE) test_main_keyfarm -C src

test_average_calculator:
	$(MAKE) test_average_calculator -C src

clean:
	$(MAKE) clean -C src

.DEFAULT_GOAL := all
.PHONY: all test_main_map test_main_keyfarm test_average_calculator clean
